"""SQLite database manager with schema initialization."""

import logging

import aiosqlite

logger = logging.getLogger("signalpilot.db.database")

SCHEMA_SQL = """\
-- Signals table: every signal generated by the system
CREATE TABLE IF NOT EXISTS signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT    NOT NULL,
    symbol          TEXT    NOT NULL,
    strategy        TEXT    NOT NULL,
    entry_price     REAL    NOT NULL,
    stop_loss       REAL    NOT NULL,
    target_1        REAL    NOT NULL,
    target_2        REAL    NOT NULL,
    quantity        INTEGER NOT NULL,
    capital_required REAL   NOT NULL,
    signal_strength INTEGER NOT NULL,
    gap_pct         REAL    NOT NULL,
    volume_ratio    REAL    NOT NULL,
    reason          TEXT    NOT NULL,
    created_at      TEXT    NOT NULL,
    expires_at      TEXT    NOT NULL,
    status          TEXT    NOT NULL DEFAULT 'sent'
);

CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(date);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_date_status ON signals(date, status);

-- Trades table: trades the user has TAKEN
CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id       INTEGER NOT NULL REFERENCES signals(id),
    date            TEXT    NOT NULL,
    symbol          TEXT    NOT NULL,
    entry_price     REAL    NOT NULL,
    exit_price      REAL,
    stop_loss       REAL    NOT NULL,
    target_1        REAL    NOT NULL,
    target_2        REAL    NOT NULL,
    quantity        INTEGER NOT NULL,
    pnl_amount      REAL,
    pnl_pct         REAL,
    exit_reason     TEXT,
    taken_at        TEXT    NOT NULL,
    exited_at       TEXT
);

CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(date);
CREATE INDEX IF NOT EXISTS idx_trades_signal_id ON trades(signal_id);
CREATE INDEX IF NOT EXISTS idx_trades_exited_at ON trades(exited_at);

-- User config table: stores user preferences
CREATE TABLE IF NOT EXISTS user_config (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    telegram_chat_id TEXT   NOT NULL,
    total_capital   REAL    NOT NULL DEFAULT 50000.0,
    max_positions   INTEGER NOT NULL DEFAULT 5,
    created_at      TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL
);
"""


class DatabaseManager:
    """Manages SQLite connection and schema initialization."""

    def __init__(self, db_path: str = "signalpilot.db") -> None:
        self._db_path = db_path
        self._connection: aiosqlite.Connection | None = None

    @property
    def connection(self) -> aiosqlite.Connection:
        """Return the active database connection."""
        if self._connection is None:
            raise RuntimeError("Database not initialized. Call initialize() first.")
        return self._connection

    async def initialize(self) -> None:
        """Open connection, enable WAL mode and foreign keys, create tables.

        Idempotent: returns immediately if already initialized so that
        repositories holding a reference to the original connection are
        not invalidated.
        """
        if self._connection is not None:
            return
        self._connection = await aiosqlite.connect(self._db_path)
        self._connection.row_factory = aiosqlite.Row
        await self._connection.execute("PRAGMA journal_mode=WAL")
        await self._connection.execute("PRAGMA foreign_keys=ON")
        await self._create_tables()
        logger.info("Database initialized at %s", self._db_path)

    async def close(self) -> None:
        """Close the database connection."""
        if self._connection:
            conn = self._connection
            self._connection = None
            await conn.close()
            logger.info("Database connection closed")

    async def _create_tables(self) -> None:
        """Create all tables defined in the schema."""
        await self.connection.executescript(SCHEMA_SQL)
        await self.connection.commit()
        await self._run_phase2_migration()
        await self._run_phase4_migration()

    async def _run_phase2_migration(self) -> None:
        """Phase 2 idempotent migration: add new columns and tables.

        Uses PRAGMA table_info() to check column existence before adding
        since SQLite lacks ADD COLUMN IF NOT EXISTS.
        """
        conn = self.connection

        async def _has_column(table: str, column: str) -> bool:
            cursor = await conn.execute(f"PRAGMA table_info({table})")
            rows = await cursor.fetchall()
            return any(row["name"] == column for row in rows)

        # signals table: add setup_type, strategy_specific_score
        if not await _has_column("signals", "setup_type"):
            await conn.execute("ALTER TABLE signals ADD COLUMN setup_type TEXT")
        if not await _has_column("signals", "strategy_specific_score"):
            await conn.execute("ALTER TABLE signals ADD COLUMN strategy_specific_score REAL")

        # trades table: add strategy
        if not await _has_column("trades", "strategy"):
            await conn.execute(
                "ALTER TABLE trades ADD COLUMN strategy TEXT NOT NULL DEFAULT 'gap_go'"
            )

        # user_config table: add strategy enabled flags
        if not await _has_column("user_config", "gap_go_enabled"):
            await conn.execute(
                "ALTER TABLE user_config ADD COLUMN gap_go_enabled INTEGER NOT NULL DEFAULT 1"
            )
        if not await _has_column("user_config", "orb_enabled"):
            await conn.execute(
                "ALTER TABLE user_config ADD COLUMN orb_enabled INTEGER NOT NULL DEFAULT 1"
            )
        if not await _has_column("user_config", "vwap_enabled"):
            await conn.execute(
                "ALTER TABLE user_config ADD COLUMN vwap_enabled INTEGER NOT NULL DEFAULT 1"
            )

        # New tables
        await conn.executescript("""
            CREATE TABLE IF NOT EXISTS strategy_performance (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                strategy        TEXT    NOT NULL,
                date            TEXT    NOT NULL,
                signals_generated INTEGER NOT NULL DEFAULT 0,
                signals_taken   INTEGER NOT NULL DEFAULT 0,
                wins            INTEGER NOT NULL DEFAULT 0,
                losses          INTEGER NOT NULL DEFAULT 0,
                total_pnl       REAL    NOT NULL DEFAULT 0.0,
                win_rate        REAL    NOT NULL DEFAULT 0.0,
                avg_win         REAL    NOT NULL DEFAULT 0.0,
                avg_loss        REAL    NOT NULL DEFAULT 0.0,
                expectancy      REAL    NOT NULL DEFAULT 0.0,
                capital_weight_pct REAL NOT NULL DEFAULT 0.0,
                UNIQUE(strategy, date)
            );

            CREATE TABLE IF NOT EXISTS vwap_cooldown (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol          TEXT    NOT NULL,
                last_signal_at  TEXT    NOT NULL,
                signal_count_today INTEGER NOT NULL DEFAULT 0
            );
        """)

        await conn.commit()
        logger.info("Phase 2 migration complete")

    async def _run_phase4_migration(self) -> None:
        """Phase 4 idempotent migration: signal_actions and watchlist tables."""
        conn = self.connection

        await conn.executescript("""
            CREATE TABLE IF NOT EXISTS signal_actions (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                signal_id       INTEGER NOT NULL REFERENCES signals(id),
                action          TEXT    NOT NULL,
                reason          TEXT,
                response_time_ms INTEGER,
                acted_at        TEXT    NOT NULL,
                message_id      INTEGER
            );

            CREATE INDEX IF NOT EXISTS idx_signal_actions_signal_id
                ON signal_actions(signal_id);
            CREATE INDEX IF NOT EXISTS idx_signal_actions_acted_at
                ON signal_actions(acted_at);

            CREATE TABLE IF NOT EXISTS watchlist (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol          TEXT    NOT NULL,
                signal_id       INTEGER REFERENCES signals(id),
                strategy        TEXT    NOT NULL DEFAULT '',
                entry_price     REAL    NOT NULL DEFAULT 0.0,
                added_at        TEXT    NOT NULL,
                expires_at      TEXT    NOT NULL,
                triggered_count INTEGER NOT NULL DEFAULT 0,
                last_triggered_at TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_watchlist_symbol
                ON watchlist(symbol);
            CREATE INDEX IF NOT EXISTS idx_watchlist_expires_at
                ON watchlist(expires_at);
        """)

        await conn.commit()
        logger.info("Phase 4 migration complete")
