"""Dashboard API routes for market regime detection."""

from __future__ import annotations

from fastapi import APIRouter, Query, Request

from signalpilot.db.regime_performance_repo import RegimePerformanceRepository
from signalpilot.db.regime_repo import MarketRegimeRepository

router = APIRouter()


@router.get("/current")
async def get_current_regime(request: Request):
    """Get today's most recent regime classification."""
    conn = request.app.state.read_conn
    repo = MarketRegimeRepository(conn)
    classifications = await repo.get_today_classifications()

    if not classifications:
        return {"regime": None, "message": "No classification today"}

    latest = classifications[-1]
    return {
        "regime": latest.regime,
        "confidence": round(latest.confidence, 4),
        "trending_score": round(latest.trending_score, 4),
        "ranging_score": round(latest.ranging_score, 4),
        "volatile_score": round(latest.volatile_score, 4),
        "india_vix": latest.india_vix,
        "nifty_gap_pct": latest.nifty_gap_pct,
        "directional_alignment": latest.directional_alignment,
        "strategy_weights": latest.strategy_weights,
        "min_star_rating": latest.min_star_rating,
        "max_positions": latest.max_positions,
        "position_size_modifier": latest.position_size_modifier,
        "is_reclassification": latest.is_reclassification,
        "previous_regime": latest.previous_regime,
        "classified_at": latest.classified_at.isoformat() if latest.classified_at else None,
    }


@router.get("/history")
async def get_regime_history(
    request: Request,
    days: int = Query(7, ge=1, le=90),
):
    """Get regime classification history."""
    conn = request.app.state.read_conn
    repo = MarketRegimeRepository(conn)
    history = await repo.get_regime_history(days)

    return [
        {
            "regime": c.regime,
            "confidence": round(c.confidence, 4),
            "india_vix": c.india_vix,
            "is_reclassification": c.is_reclassification,
            "previous_regime": c.previous_regime,
            "classified_at": c.classified_at.isoformat() if c.classified_at else None,
        }
        for c in history
    ]


@router.get("/performance")
async def get_regime_performance(
    request: Request,
    days: int = Query(30, ge=1, le=365),
):
    """Get performance metrics broken down by regime."""
    conn = request.app.state.read_conn
    repo = RegimePerformanceRepository(conn)
    summary = await repo.get_performance_summary(days)

    return [
        {
            "regime": row["regime"],
            "total_signals": row["total_signals"],
            "total_taken": row["total_taken"],
            "total_wins": row["total_wins"],
            "total_losses": row["total_losses"],
            "total_pnl": round(row["total_pnl"], 2),
            "avg_win_rate": round(row["avg_win_rate"], 4) if row["avg_win_rate"] else None,
        }
        for row in summary
    ]


@router.get("/morning-brief")
async def get_morning_brief(request: Request):
    """Get the cached morning brief text."""
    # Morning brief is generated by the lifecycle, not stored in DB
    # Return a placeholder for the dashboard to show
    return {"message": "Morning brief is delivered via Telegram at 8:45 AM."}
